name: Live Test

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Committish to checkout and test'

jobs:
  test:
    name: Live Test
    runs-on: ubuntu-latest
    environment: Live Testing
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref || github.sha }}

      - name: Run Live Tests
        run: dotnet test
          --configuration Release
          --filter="TestCategory!=Smoke&TestCategory!=Images&TestCategory!=Moderations&TestCategory!=Manual"
          --logger "trx;LogFilePrefix=live"
          --results-directory ${{github.workspace}}/artifacts/test-results
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: ${{ !cancelled() }}
        with:
          name: test-artifacts
          path: ${{github.workspace}}/artifacts
