name: Build and Test

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit SHA to checkout and test'
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build: # Test, pack and publish the Open AI nuget package as a build artifact 
    name: Build
    runs-on: ubuntu-latest
    env:
      version_suffix_args: ${{ format('--version-suffix="alpha.{0}"', github.run_number) }}
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Pack
        run: dotnet pack
          --configuration Release
          --output "${{github.workspace}}/artifacts/packages"
          ${{ env.version_suffix_args }}

      - name: Unit Test
        run: dotnet test
          --configuration Release
          --filter="TestCategory=Smoke&TestCategory!=Manual"
          --logger "trx;LogFilePrefix=smoke"
          --results-directory ${{github.workspace}}/artifacts/test-results

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: ${{ !cancelled() }}
        with:
          name: build-artifacts
          path: ${{github.workspace}}/artifacts

  test:
    name: Live Test
    needs: build
    runs-on: ubuntu-latest
    environment: Live Testing
    if: github.event_name != 'pull_request'
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Live Tests
        uses: ./.github/actions/live-test
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: ${{ !cancelled() }}
        with:
          name: test-artifacts
          path: ${{github.workspace}}/artifacts

  deploy:
    name: Publish Package
    if: github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
      - name: NuGet Autenticate
        run: dotnet nuget add source
          "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
          --name "github"
          --username ${{ github.actor }}
          --password ${{ secrets.GITHUB_TOKEN }}
          --store-password-in-clear-text
      - name: Publish
        run: dotnet nuget push
          ${{github.workspace}}/build-artifacts/packages/*.nupkg
          --source "github"
          --api-key ${{ secrets.GITHUB_TOKEN }}
          --skip-duplicate
