# This worflow is triggered on push to main, pull request, or by manual invocation.
# It builds and unit tests the codebase.
name: Build and Unit Test

on:
  workflow_dispatch:
    inputs:
      # The user can specify the committish to checkout and test using the ref input.
      # This is required because github UI only allows queuing runs for a branch or tag, not a specific commit or PR ref. 
      ref:
        description: 'Committish to checkout and test'
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build: # Test, pack and publish the Open AI nuget package as a build artifact 
    name: Build
    runs-on: ubuntu-latest
    env:
      version_suffix_args: ${{ format('--version-suffix="alpha.{0}"', github.run_number) }}
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref || github.sha }}

      - name: Build and Pack
        run: dotnet pack
          --configuration Release
          --output "${{github.workspace}}/artifacts/packages"
          ${{ env.version_suffix_args }}

      - name: Unit Test
        run: dotnet test
          --configuration Release
          --filter="TestCategory=Smoke&TestCategory!=Manual"
          --logger "trx;LogFilePrefix=smoke"
          --results-directory ${{github.workspace}}/artifacts/test-results

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: ${{ !cancelled() }}
        with:
          name: build-artifacts
          path: ${{github.workspace}}/artifacts
